### ISSUE TITLE
Error in prediction 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [Mayurji/Social-DIstancing-Using-Deep-Learning-and-OpenCV#2]
Hi , there is following error when i run the project ,  I think the weights load function is not right. 

![error2](https://user-images.githubusercontent.com/28862708/82414150-2fc7df80-9aa9-11ea-8fd4-6d7d2ef049c3.jpg)
![error1](https://user-images.githubusercontent.com/28862708/82414155-30f90c80-9aa9-11ea-96ca-52b5858c506d.jpg)

**Comment by Mayurji** [comment]
I am using pre-trained model and there is not much changes required. You need to download pre-trained model with all the config and weights files. 

![Screen Shot 2020-05-20 at 12 35 24 PM](https://user-images.githubusercontent.com/10477789/82415657-795aff00-9a96-11ea-9730-2d1a91d2a2fe.png)

**Comment by MuhammadAsadJaved** [comment]
OK. thank you very much for your time and response.
